// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqjHs-p_PEeLAC7cYquzyTof7hc8NJcHo',
    appId: '1:125511489203:android:cd431737c2f082b85a42c6',
    messagingSenderId: '125511489203',
    projectId: 'vbt-food',
    storageBucket: 'vbt-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2utvzkwZv7g6eUjk1aR7ZSQCtxLDRQU8',
    appId: '1:125511489203:ios:ac1868914cc90b7e5a42c6',
    messagingSenderId: '125511489203',
    projectId: 'vbt-food',
    storageBucket: 'vbt-food.appspot.com',
    iosClientId: '125511489203-op5l2mded5gl0f3700tqv5b3hljhgq2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.vbtfoodchallange',
  );
}
